apiVersion: v2
name: opencost
description: A Helm chart for deploying OpenCost to monitor GCP resource usage and costs
type: application
version: 0.1.0
appVersion: "1.115.0"  # Replace with actual OpenCost version if needed
