apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost-gke
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/faresdu/monitoring-stack.git
    targetRevision: main
    path: opencost
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: opencost

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

