opencost:
  clusterName: "argocd-task-cluster"

  cloudProvider: "gcp"

  gcp:
    projectID: "digital-yeti-463708-m2"  # e.g., my-private-project-123
    billingDataDataset: "opencost_task"  # e.g., gcp_billing
    pricingSource: "gcp-billing-export"

  exporter:
    enabled: true

  prometheus:
    external:
      url: ""
      port: ""
      path: ""
    internal:
      enabled: false
    service:
      enabled: false
  serviceMonitor:
    enabled: false
