---
replicaCount: 1
image:
  repository: ghcr.io/opencost/opencost
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 9003
cloudProvider: gcp
prometheusEndpoint: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
resources: {}

