apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: opencost
  template:
    metadata:
      labels:
        app: opencost
    spec:
      containers:
        - name: opencost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 9003
              name: http
          env:
            - name: OPENCOST_CLUSTER_ID
              value: "{{ .Values.cloudProvider }}"
            - name: OPENCOST_CLOUD_PROVIDER_API_KEY
              value: "{{ .Values.exporter.cloudProviderApiKey }}"
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "{{ .Values.prometheusEndpoint }}"
          resources:
            "{{- toYaml .Values.resources | nindent 12 }}"

