{{- if .Values.gcp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gcp-credentials
type: Opaque
data:
  {{- if .Values.gcp.serviceAccountKey }}
  service-account.json: {{ .Values.gcp.serviceAccountKey | quote }}
  {{- end }}
  {{- if .Values.gcp.apiKey }}
  api-key: {{ .Values.gcp.apiKey | b64enc | quote }}
  {{- end }}
---
{{- end }}
